url: https://kazanspe.github.io/
baseurl: ""

# Site settings
title: SPE КНИТУ
email: speknrtu@gmail.com
description: "Welcome to the Kazan National Research Technological University SPE Student Chapter."


# Team names, titles and social links
people:
- name: Abayomi Koyejo
  pic: 1
  position: President
  social:
    - title: twitter
      url: http://twitter.com/kabayomi007
    - title: vk
      url: http://vk.com/kabayomi
    - title: github
      url: http://github.com/kabayomi
    - title: linkedin
      url: http://www.linkedin.com/in/koyejoabayomi/

- name: Anastasia Sitalo
  pic: 2
  position: Public Relations Officer
  social:
    - title: vk
      url: https://vk.com/nastya_sitalo
    - title: instagram
      url: https://www.instagram.com/ann_sitalo/"
    - title: linkedin
      url: #

- name: Ademuwagun Temiloluwa
  pic: 3
  position: VP
  social:
    - title: vk
      url: https://vk.com/dosti4luv
    - title: facebook
      url: https://fb.com/dosti4luv
    - title: instagram
      url: https://instagram.com/dosti4luv

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: vk
    url: http://vk.com/kazanspe
  - title: facebook
    url: http://facebook.com/speknrtu
  - title: instagram
    url: https://instagram.com/fnnk.kazan
  - title: github
    url: http://github.com/kazanspe

# Postal address (add as many lines as necessary)
address:
  - line: Karl Marx 68
  - line: Sibirsky Tract 12
  - line: Kazan, Russia

# Build settings
markdown: kramdown
permalink: pretty
