url: https://kazanspe.github.io
baseurl: ""

# Site settings
title: SPE КНИТУ
email: speknrtu@gmail.com
description: "Welcome to the Kazan National Research Technological University SPE Student Chapter."


# Team names, titles and social links
people:
- name: Abayomi Koyejo
  pic: 1
  position: President
  social:
    - title: fa-university
      url: http://kabayomi.info
    - title: fa-vk
      url: http://vk.com/kabayomi
    - title: github
      url: http://github.com/kabayomi
    - title: linkedin
      url: http://www.linkedin.com/in/koyejoabayomi/

- name: Anastasia Sitalo
  pic: 2
  position: Public Relations Officer
  social:
    - title: fa-vk
      url: https://vk.com/nastya_sitalo
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Ademuwagun Temiloluwa
  pic: 3
  position: VP
  social:
    - title: fa-vk
      url: https://vk.com/dosti4luv
    - title: facebook
      url: #
    - title: fa-envelope
      url: mailto:temiloluwa26@gmail.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://vk.com/kazanspe
  - title: facebook
    url: http://facebook.com/speknrtu
  - title: stack-overflow
    url:
  - title: bitbucket
    url:
  - title: github
    url: http://github.com/kazanspe

# Postal address (add as many lines as necessary)
address:
  - line: Karl Marx 68
  - line: Sibirsky Tract 12
  - line: Kazan, Russia

# Build settings
markdown: kramdown
permalink: pretty
